# Setup
title: JJcodo
description: 最幸福的事情是睡到自然醒和躺下就入睡
url: https://jjcodo.github.io/
avatar: /avatar.jpeg
paginate: 10
permalink: pretty
cover_image: /bg.jpeg
timezone: Asia/Shanghai

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-last-modified-at
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
twitter:
  username: Daniel
  card: summary
logo: logo.png
social:
  name: Daniel
  links:
    - https://twitter.com/vszhub
    - https://github.com/vszhub

google_site_verification: xxxxx
lang: zh-CN
sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Daniel
  url: https://jjcodo.github.io/
  email: danielcoder@foxmail.com

lucene_enabled: false

defaults:
  - scope:
      path: ""
      type: "collections"
    values:
      output: true
github:
  is_project_page: false