# Setup
title: JJcodo
description: 最幸福的事情是睡到自然醒和躺下就入睡
url: https://jjcodo.github.io/
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
twitter:
  username: Daniel
  card: summary
logo: logo.png
social:
  name: Daniel
  links:
    - https://twitter.com/vszhub
    - https://github.com/vszhub

google_site_verification: xxxxx
lang: zh-CN
sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Daniel
  url: https://jjcodo.github.io/
  email: danielcoder@foxmail.com
