# Setup
title: JJcodo
description: 最幸福的事情是睡到自然醒和躺下就入睡
url: https://jjcodo.github.io/
avatar: /avatar.jpeg
paginate: 10
permalink: pretty
cover_image: /bg.jpeg
timezone: Asia/Shanghai
last_modified_at:
  date_format: "%Y-%m-%d %H:%M:%S %z"
# Gems

plugins:
  - jekyll-last-modified-at
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-toc
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-remote-theme
  - jekyll-timeago
  - rouge

markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  syntax_highlighter: rouge
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    default_lang: assembly
    css_class: highlight
    span:
      line_numbers: true

safe: false

highlighter: rouge
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
twitter:
  username: Daniel
  card: summary
logo: logo.png
social:
  name: Daniel
  links:
    - https://twitter.com/vszhub
    - https://github.com/vszhub

google_site_verification: xxxxx
lang: zh-CN
sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Daniel
  url: https://jjcodo.github.io/
  email: danielcoder@foxmail.com

lucene_enabled: false

github:
  is_project_page: false


