source "https://rubygems.org"
gemspec

gem 'jekyll-compose', group: [:jekyll_plugins]

gem "webrick", "~> 1.8"
gem 'tzinfo'
gem 'tzinfo-data'
gem 'jekyll-last-modified-at'
gem 'rouge'
gem 'jekyll-timeago'
gem 'jekyll-remote-theme'
gem 'jekyll-mentions'
gem 'jemoji'
gem 'jekyll-avatar'
gem 'jekyll-sass-converter'
gem 'jekyll-redirect-from'
gem 'jekyll-toc'
gem 'jekyll-admin'
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem "jekyll-spaceship"
gem "jekyll-markdown-it" 
gem 'jekyll-paginate-v2'